# Define variables at the top
substitutions:
  _PROJECT_ID:
  _PROJECT_REGION:
  _SERVICE_NAME:
  _IMAGE_NAME: 
  _CONTAINER_REGION: 
  _TARGET_PROJECT: 

steps:
  # Step 1: Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      # Tag the image with the project ID and a unique tag (e.g., commit SHA)
      - "${_CONTAINER_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}"  
      - "."  # Build context (current directory)

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_CONTAINER_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}' # Push the tagged image to GCR

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "deploy"
      - "${_PROJECT_ID}"
      - "--image"
      - "${_CONTAINER_REGION}/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_PROJECT_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--async"

timeout: 1200s